name: websocket_tracker
description: A simple app to monitor Socket.IO messages.
version: 0.1.0+1

# Remove this line if you wish to publish to pub.dev
publish_to: 'none' 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Network Utilities
  socket_io_client: ^0.9.12

  # iOS Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
